### ISSUE TITLE
Crear ventana de ajustes

### ISSUE THREAD

**Issue by franloza** [franloza/AW#11]
Sería una pantalla parecida al formulario de registro en el que se puedan modificar los datos personales, subir nueva documentación, cambiar el avatar...Tiene que cambiar para cada rol (Igual que en el registro).

Se puede reutilizar bastante código de FormularioRegistro para hacer FormularioAjustes

**Comment by Whitenorris** [comment]
Terminado

**Comment by franloza** [comment]
Adaptar los ajustes de empresa al perfil de empresa. Avisar para crear columnas en la BBDD
