### ISSUE TITLE
Ampliar campos de oferta

### ISSUE THREAD

**Issue by franloza** [franloza/AW#17]
En oferta se debe aumentar el numero de campos para poder meter más información. Se deberá incluir las aptitudes asociadas a la oferta(ver issue relacionado con esto), se debe incluir los siguientes campos:
- Descripcion: Aumentar el tamaño a longtext en la BBDD para aceptar grandes textos
- Requisitos mínimos
- Idiomas
- Requisitos deseables

**Comment by alexmartin3** [comment]
Faltan añadir las aptitudes cuando esten implementadas
