### ISSUE TITLE
Funcionalidad contratos

### ISSUE THREAD

**Issue by franloza** [franloza/AW#20]
Esta funcionalidad implica varios puntos, parecidos al de las ofertas y demandas
-   Crear tabla en BBDD
  - Crear ContratosDAO con los metodos correspondiente
  - La novedad en este punto surge en el portal estudiante. Si el estado aperece en un contrato que esté en curso, se dejará de mostrar el contenido de ofertas y se mostrará un mensaje del tipo "No puede ver las ofertas disponible. Usted tiene un contracto en vigor con la empresa tal..." Se puede mostrar información del contrato. Reutilizar el dialogo modal del administrador de contratos (ver issue)
- En administrador y empresa, hacer algo parecido a con las ofertas y demandas y mostrar las tablas con los contratos clasificados y sus correspondientes dialogos modales (ver issue)

**Comment by alexmartin3** [comment]
me pregunto yo si en el portal de estudiantes, en lugar de solo salir contrato en el caso de que tenga alguno, al meterse en ofertas y darle el aviso, no debería haber un pestaña para que consulte su contrato, y por si acaso tiene contratos anteriores que ya hayan finalizado¿?

SI se mete a ofertas, redirigirle al contrato que tiene en vigor, pero tener una pestaña contrato con una fila que sea su contrato actual (dialogo modal si pincha) y en caso de haber tenido mas contratos finalizados aparecer debajo seguidos.... no¿? comentad

**Comment by franloza** [comment]
Considero que eso implica curro extra que podría considerarse si terminamos todos los issues abiertos. De momento, dejaría con que hubiera una condición de que si tiene un contrato activo, la pestaña ofertas se cambiara por una que le mostrara el contrato (Si cambiar el menú no implica demasiado jaleo, tambien cambiaría el menú para ese caso)

**Comment by franloza** [comment]
Las funciones basicas del DAO están implementadas. Falta testeo
