### ISSUE TITLE
Dialogos modales para ampliar información

### ISSUE THREAD

**Issue by franloza** [franloza/AW#21]
Esto aplica a Ofertas, Demandas y Contratos de todos los portales. En cada tabla que aparece en el portal, se debe poder clickar en cada fila y que se abra un dialogo modal que muestre la información ampliada de cada oferta, demanda o contrato.  Se puede quizas implementar con herencia de tipo Modal.php y extender ofertaModal.php, demandaModal.php y contratoModal.php

**Comment by pmdp** [comment]
He hablado con Iván de este tema y me ha dicho que la mejor forma es: Poner una propiedad data-id (customizada) en cada tr (fila) de la tabla, para que al clickarla se haga una petición AJAX con el id de la oferta en concreto y el código php se encargue de devolver un JSON con toda la finformación de la oferta, este JSON lo recibe el jquery del lado del cliente y se encarga de montar y mostrar el dialogo modal.
