### ISSUE TITLE
Arregar Titlebar

### ISSUE THREAD

**Issue by franloza** [franloza/AW#6]
Los iconos del titlebar no se ven. No hace falta crear aun "settings.php" y "notifications.php". Si se tiene que linkar el botón de logout al método apropiado (Ya está implementado)

**Comment by franloza** [comment]
Iconos ya se ven. Falta linkar el logout a su correspondiente icono.

**Comment by pmdp** [comment]
He pensado en como hacer el logout, pero no lo tengo muy claro, ¿¿habría que hacer un logout.php que llame a $app -> logout()?? Por que he intentado poner href="<?php $app -> logout(); ?>" en la etiqueta a que corresponde a la de deslogearse y no fula. Además tendría que llevar al index no?

**Comment by franloza** [comment]
Resuelto:
Justo es la idea que has dicho tu pepe, pero en href una petición GET al mismo dashboard.php con logout como parametro. Se mete una condición: if(isset($_GET['logout])) {**$app -> logout()**};

Gracias!
